homepage_settings:
  countdown:
    show: true
    timezone: Canada/Vancouver
    deadline: 2024-02-04 23:59
  modal:
    show: false
    delay: 5000
  testimonials:
    show: true
    title: "Attendees about Code BEAM"
  gallery:
    show: false
    title: "Code BEAM Europe 2024"
  tickets: true
